/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/hi" |
  "/pages/login" |
  "/pages/address/edit" |
  "/pages/address/list" |
  "/pages/agents/chat" |
  "/pages/agents/index" |
  "/pages/agreement/privacy-policy" |
  "/pages/agreement/user-agreement" |
  "/pages/order/list" |
  "/pages/order/result" |
  "/pages/product/detail" |
  "/pages/profile/index" |
  "/pages/order/confirm/index";

interface NavigateToOptions {
  url: _LocationUrl
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void
}

declare module 'virtual:uni-pages' {
  export type LocationUrl = _LocationUrl
}
