#!/usr/bin/env tsx
/**
 * Enum Sync Script
 *
 * Reads Prisma schema enums and generates:
 * 1. Zod enum definitions in infra/shared/src/enums.ts
 * 2. Frontend Select option constants in apps/admin/src/shared/constants/enums.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(process.cwd());

const schemaPath = path.join(projectRoot, 'infra/database/prisma/schema.prisma');
const sharedEnumsPath = path.join(projectRoot, 'infra/shared/src/enums.ts');
const adminEnumsPath = path.join(projectRoot, 'apps/admin/src/shared/constants/enums.ts');

// Chinese label mapping for common enum values
const LABEL_MAP: Record<string, string> = {
  PENDING: '待处理',
  ACTIVE: '启用',
  INACTIVE: '停用',
  CONFIRMED: '已确认',
  SHIPPED: '已发货',
  DELIVERED: '已送达',
  CANCELLED: '已取消',
  COMPLETED: '已完成',
  FAILED: '失败',
  SUCCESS: '成功',
  DRAFT: '草稿',
  PUBLISHED: '已发布',
  ARCHIVED: '已归档',
  APPROVED: '已批准',
  REJECTED: '已拒绝',
  ENABLED: '启用',
  DISABLED: '禁用',
  PUBLIC: '公开',
  PRIVATE: '私有',
  READONLY: '只读',
};

function getLabel(value: string): string {
  return LABEL_MAP[value] || value;
}

interface PrismaEnum {
  name: string;
  values: string[];
}

function parsePrismaEnums(): PrismaEnum[] {
  const content = fs.readFileSync(schemaPath, 'utf-8');
  const enums: PrismaEnum[] = [];

  const enumRegex = /enum\s+(\w+)\s*\{([^}]+)\}/g;
  let match: RegExpExecArray | null;

  while ((match = enumRegex.exec(content)) !== null) {
    const name = match[1];
    const values = match[2]
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('//'));

    enums.push({ name, values });
  }

  return enums;
}

function generateZodEnums(enums: PrismaEnum[]): string {
  const lines = [
    '// Auto-generated by enum-sync — do not edit manually',
    "import { z } from 'zod';",
    '',
  ];

  for (const e of enums) {
    const valuesStr = e.values.map((v) => `'${v}'`).join(', ');
    lines.push(`export const ${e.name}Enum = z.enum([${valuesStr}]);`);
    lines.push(`export type ${e.name} = z.infer<typeof ${e.name}Enum>;`);
    lines.push('');
  }

  return lines.join('\n');
}

function generateSelectOptions(enums: PrismaEnum[]): string {
  const lines = ['// Auto-generated by enum-sync — do not edit manually', ''];

  for (const e of enums) {
    const options = e.values.map((v) => `  { label: '${getLabel(v)}', value: '${v}' },`).join('\n');
    lines.push(`export const ${e.name}Options = [`);
    lines.push(options);
    lines.push('] as const;');
    lines.push('');
  }

  return lines.join('\n');
}

function main() {
  const enums = parsePrismaEnums();

  if (enums.length === 0) {
    console.log('No Prisma enums found in schema.prisma.');
    console.log('All enum-like fields currently use String type.');
    console.log('Add enum blocks to schema.prisma and re-run this script.');
    return;
  }

  console.log(`Found ${enums.length} enum(s): ${enums.map((e) => e.name).join(', ')}`);

  // Ensure directories exist
  fs.mkdirSync(path.dirname(sharedEnumsPath), { recursive: true });
  fs.mkdirSync(path.dirname(adminEnumsPath), { recursive: true });

  // Generate Zod enums
  const zodContent = generateZodEnums(enums);
  fs.writeFileSync(sharedEnumsPath, zodContent);
  console.log(`✓ Generated Zod enums: ${sharedEnumsPath}`);

  // Generate Select options
  const optionsContent = generateSelectOptions(enums);
  fs.writeFileSync(adminEnumsPath, optionsContent);
  console.log(`✓ Generated Select options: ${adminEnumsPath}`);

  console.log('\nNext: Run `pnpm -C infra/shared build` to rebuild the shared package.');
}

main();
